[wokwi]
version = 1
#elf = ".pio/build/PontTournant.ino.elf"
#firmware = ".pio/build/PontTournant.ino.hex"
elf = "../../.pio/build/lucidgloves-prototype3/firmware.elf"
firmware = "../../.pio/build/lucidgloves-prototype3/firmware.bin"
