name: "Pont tournant"

on:
  workflow_dispatch:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: / # directory with wokwi.toml, relative to repo's root
          timeout: 10000
          expect_text: 'Hello'
          fail_text: 'Error'
          # scenario: 'button.test.yaml'
          serial_log_file: 'log-pontTourant.txt'
