name: 'Wokwi PontTournant'
description: 'This action tests your firmware builds with the Wokwi Simulator'

on:
  workflow_dispatch:

push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: / # directory with wokwi.toml, relative to repo's root
          timeout: 10000
          expect_text: 'Hello'
          fail_text: 'Error'
          # scenario: 'button.test.yaml'
          serial_log_file: 'log-pontTourant.txt'
          
runs:
  using: 'composite'
  steps:
    - name: Install wokwi-cli
      run: |
        wget -q -O /usr/local/bin/wokwi-cli https://github.com/wokwi/wokwi-cli/releases/latest/download/wokwi-cli-linuxstatic-x64
        chmod +x /usr/local/bin/wokwi-cli
      shell: bash
    - run: |
        wokwi-cli --timeout "${{ inputs.timeout }}" --expect-text "$CI_EXPECT_TEXT" \
          ${{ inputs.diagram_file != '' && format('--diagram-file "{0}"', inputs.diagram_file) || '' }} \
          ${{ inputs.elf != '' && format('--elf "{0}"', inputs.elf) || '' }} \
          --fail-text "$CI_FAIL_TEXT" --scenario "${{ inputs.scenario }}" "${GITHUB_WORKSPACE}/${{ inputs.path }}" \
          --serial-log-file "${{ inputs.serial_log_file }}"
      env:
        WOKWI_CLI_TOKEN: ${{ inputs.token }}
        FORCE_COLOR: 2  # Enables color output - see https://github.com/chalk/supports-color/issues/106
        CI_EXPECT_TEXT: ${{ inputs.expect_text }}
        CI_FAIL_TEXT: ${{ inputs.fail_text }}
      shell: bash
